### ISSUE TITLE
Omeka-S v4 compatibility

### ISSUE THREAD

**Issue by hxsllc** [Daniel-KM/Omeka-S-module-Ebook#13]
We are exploring archive/preservation options, including the pdiiif library.

We just discovered this module and tried installing it in Omeka-S v4 by updating the config/module.ini.

It does install without error and presents the admin screen (past jobs) as well as the actions.

I don't know if this is the first issue or the only issue, but here's what I see when trying to run the action "Create ebook with selected".

```
TypeError: Argument 2 passed to Laminas\Form\Fieldset::__construct() must be of the type array, null given, called in /var/www/edisondigital/modules/Ebook/src/Service/Form/EbookFormFactory.php on line 12 and defined in /var/www/edisondigital/vendor/laminas/laminas-form/src/Fieldset.php:75
Stack trace:
#0 /var/www/edisondigital/modules/Ebook/src/Service/Form/EbookFormFactory.php(12): Laminas\Form\Fieldset->__construct()
#1 /var/www/edisondigital/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(615): Ebook\Service\Form\EbookFormFactory->__invoke()
#2 /var/www/edisondigital/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(234): Laminas\ServiceManager\ServiceManager->doCreate()
#3 /var/www/edisondigital/vendor/laminas/laminas-servicemanager/src/AbstractPluginManager.php(171): Laminas\ServiceManager\ServiceManager->get()
#4 /var/www/edisondigital/vendor/laminas/laminas-form/src/FormElementManager.php(336): Laminas\ServiceManager\AbstractPluginManager->get()
#5 /var/www/edisondigital/application/src/Mvc/Controller/Plugin/GetForm.php(33): Laminas\Form\FormElementManager->get()
#6 [internal function]: Omeka\Mvc\Controller\Plugin\GetForm->__invoke()
#7 /var/www/edisondigital/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(275): call_user_func_array()
#8 /var/www/edisondigital/modules/Ebook/src/Controller/Admin/EbookController.php(256): Laminas\Mvc\Controller\AbstractController->__call()
#9 /var/www/edisondigital/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(71): Ebook\Controller\Admin\EbookController->createAction()
#10 /var/www/edisondigital/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\Controller\AbstractActionController->onDispatch()
#11 /var/www/edisondigital/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners()
#12 /var/www/edisondigital/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(97): Laminas\EventManager\EventManager->triggerEventUntil()
#13 /var/www/edisondigital/vendor/laminas/laminas-mvc/src/DispatchListener.php(132): Laminas\Mvc\Controller\AbstractController->dispatch()
#14 /var/www/edisondigital/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\DispatchListener->onDispatch()
#15 /var/www/edisondigital/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners()
#16 /var/www/edisondigital/vendor/laminas/laminas-mvc/src/Application.php(325): Laminas\EventManager\EventManager->triggerEventUntil()
#17 /var/www/edisondigital/index.php(21): Laminas\Mvc\Application->run()
#18 {main}
```

**Comment by Daniel-KM** [comment]
Hi,
The module is upgraded for Omeka S v4 in version 3.4.10.
