### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by moodyblue** [Daniel-KM/Omeka-S-module-Ebook#5]
How can I help ? Alpha.2 does not work in my environment, probably because portuguese is used.

**Comment by Daniel-KM** [comment]
What is the issue? 
For translation, you take this file : https://github.com/Daniel-KM/Omeka-S-module-Ebook/blob/master/language/template.pot and you translate it in your language with a `po` éditor, like poedit or online editors.

**Comment by moodyblue** [comment]
Omeka-S version: 1.4.0
Ebook version: Alpha.2
Steps to reproduce: Click `Create eBook` produces following message:

```
 Zend\Form\Exception\InvalidElementException
A plugin by the name "LocaleSelect" was not found in the plugin manager Zend\Form\FormElementManager\FormElementManagerV3Polyfill

Detalhes:

Zend\Form\Exception\InvalidElementException: A plugin by the name "LocaleSelect" was not found in the plugin manager Zend\Form\FormElementManager\FormElementManagerV3Polyfill in /var/www/html/omeka-s/vendor/zendframework/zend-form/src/FormElementManager/FormElementManagerTrait.php:41
Stack trace:
#0 /var/www/html/omeka-s/vendor/zendframework/zend-form/src/Factory.php(117): Zend\Form\FormElementManager\FormElementManagerV3Polyfill->get('LocaleSelect')
#1 /var/www/html/omeka-s/vendor/zendframework/zend-form/src/Form.php(176): Zend\Form\Factory->create(Array)
#2 /var/www/html/omeka-s/modules/Ebook/src/Form/EbookForm.php(124): Zend\Form\Form->add(Array)
#3 /var/www/html/omeka-s/vendor/zendframework/zend-form/src/FormElementManager/FormElementManagerV3Polyfill.php(235): Ebook\Form\EbookForm->init()
#4 /var/www/html/omeka-s/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(779): Zend\Form\FormElementManager\FormElementManagerV3Polyfill->callElementInit(Object(Zend\ServiceManager\ServiceManager), Object(Ebook\Form\EbookForm))
#5 /var/www/html/omeka-s/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(200): Zend\ServiceManager\ServiceManager->doCreate('Ebook\\Form\\Eboo...')
#6 /var/www/html/omeka-s/vendor/zendframework/zend-servicemanager/src/AbstractPluginManager.php(152): Zend\ServiceManager\ServiceManager->get('Ebook\\Form\\Eboo...')
#7 /var/www/html/omeka-s/vendor/zendframework/zend-form/src/FormElementManager/FormElementManagerTrait.php(50): Zend\ServiceManager\AbstractPluginManager->get('Ebook\\Form\\Eboo...', NULL, true)
#8 /var/www/html/omeka-s/application/src/Mvc/Controller/Plugin/GetForm.php(33): Zend\Form\FormElementManager\FormElementManagerV3Polyfill->get('Ebook\\Form\\Eboo...', NULL)
#9 [internal function]: Omeka\Mvc\Controller\Plugin\GetForm->__invoke('Ebook\\Form\\Eboo...')
#10 /var/www/html/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(276): call_user_func_array(Object(Omeka\Mvc\Controller\Plugin\GetForm), Array)
#11 /var/www/html/omeka-s/modules/Ebook/src/Controller/Admin/EbookController.php(195): Zend\Mvc\Controller\AbstractController->__call('getForm', Array)
#12 /var/www/html/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): Ebook\Controller\Admin\EbookController->createAction()
#13 /var/www/html/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#14 /var/www/html/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#15 /var/www/html/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(106): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#16 /var/www/html/omeka-s/vendor/zendframework/zend-mvc/src/DispatchListener.php(138): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#17 /var/www/html/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#18 /var/www/html/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#19 /var/www/html/omeka-s/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#20 /var/www/html/omeka-s/index.php(21): Zend\Mvc\Application->run()
#21 {main}```

**Comment by Daniel-KM** [comment]
This LocaleSelect is a core element since two years, it is used in the main parameters to set the locale. So your error is strange. Do you use another module?

**Comment by moodyblue** [comment]
Currently I have these modules active
![imagem](https://user-images.githubusercontent.com/6073615/56502261-a478c500-6509-11e9-9bc3-9b9a8f6f858a.png)

**Comment by Daniel-KM** [comment]
Can you try the version alpha3?

**Comment by moodyblue** [comment]
Now seems Ok, thanks.
